### ISSUE TITLE
[Metroid Prime Remastered]  Unable to make jumps with FPS mods.

### ISSUE THREAD

**Issue by EnderMaster77** [Fl4sh9174/Switch-Ultrawide-Mods#22]
For whatever reason, enabling your increased FPS mods in metroid Prime Remastered makes it so that samus is unable to jump gaps she normally should. Below is a comparison. Xray visor is enabled for visibility, as this room is really dark. Also, in the videos, some of your other mods are being used. This issue still happens with all other mods disabled.

Without Mod

https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/107213915/33f2c2d9-0377-43ae-8f9d-241c80c65828

With Mod

https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/assets/107213915/41a164e8-6c84-4af8-a60a-03b90bd0aaed

**Comment by Fl4sh9174** [comment]
Thanks for the feedback, other users reported the same behavior, so i made a "workaround" for it till i find a definitive solution for this problem, since the mod is only affecting the double jump, the math for fixing this second jump is very complex, i posted the cheat on gamebanana, you can check the detail on that page: https://gamebanana.com/mods/505408
