### ISSUE TITLE
Why is the ultrawide mod for Zelda Echoes of Wisdom so perfect?

### ISSUE THREAD

**Issue by liunice** [Fl4sh9174/Switch-Ultrawide-Mods#43]
I tested so many of your ultrawide mods, like Mario Rabbids Kingdom Battle, Link's Awakening, etc. However they all have one common issue: all the 2D assets in game are not perfectly round, like they are all flattened. But this time in Zelda Echoes of Wisdom, all 2D assets like controller button icons are 100% round, no visual glitches at all.

How could you accomplish this? That's amazing!

**Comment by Fl4sh9174** [comment]
It depends on the engine itself, some engines like unreal and unity, the aspect ratio is tied to the resolution, in first party games of nintendo it can vary between em, Mario Rabbids for example its not perfect since i made a hacky ultrawide patch, but its better than the stretched version, im glad you liked the mod, enjoy!
