### ISSUE TITLE
nikoderiko mods

### ISSUE THREAD

**Issue by rakantoh** [Fl4sh9174/Switch-Ultrawide-Mods#55]
Hi. the nikoderiko mods no works properly in yuzu emus, the 21.9 ultrawide mod in the start, when the characters speak between them, the image freezes, and after the audio freezes too, and the emu after some seconds closes. this same mod and the level of detail run the game at 60fps, and the 120fps mod, at least in yuzu emus, no works too. With level of detail mod i feel that not do anything, this in both emus (yuzus and ryujinx). please fix.

PD: is difficult or hard make mods? i want to learn but i no idea where to start

**Comment by Fl4sh9174** [comment]
Use Sudachi or Ryujinx in this game.

**Comment by rakantoh** [comment]
as i said, in yuzu emus 21.9 mod freezes when characters speak in the start, this include sudachi (yuzu emu), and in ryujinx the game itself (without any mod) have a issue with the image/render. For the problem with fps mod, deleted the v1.0.0 from the exefs folder and rename the 1.0.0v2 to 1.0.1v2, and the fps mod works now, in both emus, so, please fix the 21.9 mod. Thanks.

**Comment by Fl4sh9174** [comment]
send a picture or video of where it freeze, because i played the first 2 levels and worked fine.

**Comment by rakantoh** [comment]
here the link to video, i used torzu, but this happens in any yuzu emu, the freeze occurs in any part of the characters dialogue, of course if i skip with "b", i can play the levels, but i think that if exist more dialogs the game will crash too.

https://youtu.be/p-KruuBMqvI

**Comment by Fl4sh9174** [comment]
Thanks for the video, i fixed it already, wasnt the ultrawide mod crashing it, was the resolution, game cant handle resolution above 2K in the dialogues, thats why it was crashing, 1 removed the 4K mod as well, since other users can suffer from the same issue in dialogues, i updates the zip with fixes already: https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/blob/main/Nikoderiko%20the%20Magical%20World%20%5B21.9%20Ultrawide%20v1.0.1%5D.zip
